# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37ec08f3c100969a9b904ef43e6641b86b378ee1364c542a2074d308a16bd2cfefd3969856e14ced4f74d377c0fdd50517998f00ee7fa16feeb37df69f2c215

test:
  secret_key_base: 733d964d403d77c85dbe5ed6a0c33aff35bc63585814baba541e95d57a8ef0ed233ad900cb52139ad92160628956cfd92c94180e8b01c432db267ff3f5f2340b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
